<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * defaultTitle
 *
 * defaultDescription
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for appCloseGet
     *
     * .
     *
     */
    public function testAppCloseGet()
    {
    }

    /**
     * Test case for appDelete
     *
     * .
     *
     */
    public function testAppDelete()
    {
    }

    /**
     * Test case for appKillGet
     *
     * .
     *
     */
    public function testAppKillGet()
    {
    }

    /**
     * Test case for appOpenGet
     *
     * .
     *
     */
    public function testAppOpenGet()
    {
    }

    /**
     * Test case for appPut
     *
     * .
     *
     */
    public function testAppPut()
    {
    }

    /**
     * Test case for audioRecordDelete
     *
     * .
     *
     */
    public function testAudioRecordDelete()
    {
    }

    /**
     * Test case for audioRecordGet
     *
     * .
     *
     */
    public function testAudioRecordGet()
    {
    }

    /**
     * Test case for clipboardGet
     *
     * .
     *
     */
    public function testClipboardGet()
    {
    }

    /**
     * Test case for clipboardPost
     *
     * .
     *
     */
    public function testClipboardPost()
    {
    }

    /**
     * Test case for notificationCreateGet
     *
     * .
     *
     */
    public function testNotificationCreateGet()
    {
    }

    /**
     * Test case for notificationDelete
     *
     * .
     *
     */
    public function testNotificationDelete()
    {
    }

    /**
     * Test case for pingGet
     *
     * .
     *
     */
    public function testPingGet()
    {
    }

    /**
     * Test case for rebootGet
     *
     * .
     *
     */
    public function testRebootGet()
    {
    }

    /**
     * Test case for screenLockGet
     *
     * .
     *
     */
    public function testScreenLockGet()
    {
    }

    /**
     * Test case for screenOffGet
     *
     * .
     *
     */
    public function testScreenOffGet()
    {
    }

    /**
     * Test case for screenOnGet
     *
     * .
     *
     */
    public function testScreenOnGet()
    {
    }

    /**
     * Test case for screenRecordDelete
     *
     * .
     *
     */
    public function testScreenRecordDelete()
    {
    }

    /**
     * Test case for screenRecordGet
     *
     * .
     *
     */
    public function testScreenRecordGet()
    {
    }

    /**
     * Test case for screenUnlockGet
     *
     * .
     *
     */
    public function testScreenUnlockGet()
    {
    }

    /**
     * Test case for shutdownGet
     *
     * .
     *
     */
    public function testShutdownGet()
    {
    }

    /**
     * Test case for toastCreateGet
     *
     * .
     *
     */
    public function testToastCreateGet()
    {
    }

    /**
     * Test case for urlOpenGet
     *
     * .
     *
     */
    public function testUrlOpenGet()
    {
    }
}
